### PR TITLE
Add memory maps

### PR DESCRIPTION
**Pull request by celerizer**

### CODE REVIEW

**Comment by leiradel** [comment]
Not sure why this was rushed... The code seems to do the wrong thing on anything other than the Spectrum 48K.

**Comment by twinaphex** [comment]
Alright, you can push a corrected version of this onto master.

**Comment by twinaphex** [comment]
An update to FUSE would be nice as well ,users tell us this core is heavily outdated at this point.

**Comment by leiradel** [comment]
I was just pointing out that the code might be wrong as I'm not sure @celerizer is aware of all ZX Spectrum models out there, it doesn't mean I want to code it myself.

**Pull request merged**
