### PR TITLE
add memory hooks for cheat/rumble

### PR DESCRIPTION
**Pull request by RetroSven**

### CODE REVIEW

**Comment by leiradel** [comment]
@RetroSven This patch doesn't correctly return the amount of memory for each supported system. This core emulates a number of different ZX Spectrum models, each with it's own RAM capacity. The correct amount must be returned in each case.

**Comment by RetroSven** [comment]
same story as 81 - everything appears to tie back to RAM defined here:

fuse/spectrum.c:libspectrum_byte RAM[ SPECTRUM_RAM_PAGES ][0x4000];

So the size appears fine.

**Comment by leiradel** [comment]
The same comment I did in the 81-libretro core applies here. Cores must only report the actual emulated memory size, we should never take the shortcut of assuming that just because, say, there's a 1 Mb buffer in the core for the system RAM, that this is the actual system RAM size. Imagine if there's a maintenance and the buffer is dynamically allocated to the exact size needed. With your change, nothing would prevent the frontend from accessing memory past the end of the buffer.

You're also reporting 16 Kb of ROM as system RAM in this core, I believe.

**Comment by leiradel** [comment]
I've commented there.

**Pull request merged**
