### PR TITLE
Floating bus for ZX Spectrum +2A/+3 and alternative palettes

### PR DESCRIPTION
**Pull request by jfroco**
### Floating bus support for ZX Spectrum +2A/+3

- Add floating bus support for ZX Spectrum +2A/+3
- Games tested:
   - A Yankee in Irak 1.3.3
   - Mr. Kung Fu 1.3 +2a/+3 version
   - MONJAS 1.6 - Spanish
   - MONJAS 1.6 - English
   - Hell Yeah! v210131
   - Sidewize  +2A:+3 fix by Ast. A. Moore

A Yankee in Iraq v1 3 3 (Turbo Loader)-241123-121808
[ Image: A Yankee in Iraq - first game to support the +2A/+3 floating bus technique]

Development notes:

1.-  Not implemented and not really necessary to run the games:
     - Check if 128k paging is enabled
     - Return value = 0xff or last value that was written to, or read from, contended memory duringle idle intervals
2.- Timing correction for +2a/+3, only for spectrum_unattached_port_amstrad:
`It has been observed that on ULA based machines, the timings may be one tstate later than normal. All timings given in this document are for "early timing"; for "late timing", simply add one to add T-state counts given. Machines based on the Amstrad gate array do not exhibit this behaviour
`

References:
*   https://sinclair.wiki.zxnet.co.uk/wiki/Contended_memory#Timing_differences
*   https://worldofspectrum.org/forums/discussion/55142/need-help-from-people-with-a-2a-3/p8
*   http://sky.relative-path.com/zx/floating_bus.html
*   https://sourceforge.net/p/fuse-emulator/bugs/360/
*   https://www.usebox.net/jjm/blog/zx-spectrum-floating-bus/
*   https://softspectrum48.weebly.com/notes/category/floating-bus
*   https://sinclair.wiki.zxnet.co.uk/wiki/Floating_bus

### Alternative palettes

- Add alternative palettes:
   - Fuse original
   - ZX Spectrum (Wikipedia)
   - Black and White TV
   - Green monochrome monitor (from ZXSpin)
   - Ambar monochrome monitor (from ZXSpin)
   - C64-like
   - CGA 4 colours
   - CGA 8 colours
   - CGA 15 colours
   - Inverted colours
- Configurable in Quick Menu -> Core Options -> Colour Palette

Manic Miner (1983)(Software Projects)-241123-121121
[ Image: Manic Miner - Ambar mochrome monitor palette ]

Manic Miner (1983)(Software Projects)-241123-121451
[ Image: Manic Miner - CGA 4 colours palette ]

### CODE REVIEW

**Comment by zzedmore** [comment]
No idea what this all means but thanks for continuing to update this core. It's my favourite machine. 

I noticed that they finally added Currah Speech according to the Sourceforge page. This is an iconic feature and hope you can add it to your list of additions ?

Thanks for your work !

**Comment by jfroco** [comment]
> No idea what this all means but thanks for continuing to update this core. It's my favourite machine.
> 
> I noticed that they finally added Currah Speech according to the Sourceforge page. This is an iconic feature and hope you can add it to your list of additions ?
> 
> Thanks for your work !

Hello @zzedmore,

I didn't know about the Currah Microspeech support. Thank you for letting me know. I'll add it to the list.

I currently have a couple of things in my backlog, so please be patient.

Best regards!

**Comment by DSkywalk** [comment]
@jfroco Sorry, why add C64 palette and CGA?
Spectrum didn't have anything like that, it's a custom change that shouldn't have been added :thinking:

**Comment by jfroco** [comment]
> @jfroco Spectrum didn't have anything like that, it's a custom change that shouldn't have been added 🤔

You can say the same about fast tape loading, snapshot file formats, save states, etc.  And like those features, the custom palette is optional, so if you don't like it and don't want to use it... just don't.
From a technical point of view, it is the prelude to a major feature available in other emulators (and some real machines), but comments like yours discourage me from doing anything, to be honest.

**Comment by jfroco** [comment]
> @jfroco Sorry, why add C64 palette and CGA? Spectrum didn't have anything like that, it's a custom change that shouldn't have been added 🤔

@DSkywalk 
You can say the same about fast tape loading, snapshot file formats, save states, etc. And like those features, the custom palette is optional, so if you don't like it and don't want to use it... just don't.
From a technical point of view, it is the prelude to a major feature available in other emulators (and some real machines), but comments like yours discourage me from doing anything, to be honest.

**Comment by HeuristicPerson** [comment]
I don´t see the point of adding such a feature, adding unnecessary complexity to the code with something purely cosmetic that will distract from the main goal of the emulator. If you really want to tweak the palette in RetroArch, IMHO, the most logical way would be to write a shader.

**Comment by leiradel** [comment]
@jfroco have you submitted the fix to the floating bus to Fuse? I think it would be great.

**Comment by DSkywalk** [comment]
I don't feel like starting a discussion that won't lead to anything really useful. But comparing such an important feature as fast loading with putting palettes that never existed in ZX is a cosmetic that doesn't add anything and as I was going to say, you could do it perfectly well using a shader... It seems to me something quite simple to understand.

I started my comment with an ‘Sorry’, without trying to start a bad time for you. I think your ‘Floating bus’ contribution is great, but the palette is a custom thing that will be fine for you, but (sorry) it shouldn't have been merged.

And about your "discourage", I'm sorry to say that our _payment_ is to see how our contributions improve the emulation or support and to see people enjoy it. Two devs talking about whether something can be improved or may not be suitable (if you really like devs cool things), it shouldn't take away your motivation to collaborate here or wherever you feel like it :+1:

**Comment by jfroco** [comment]
@DSkywalk 
1.- "Sorry," but you are wrong: custom palettes have existed for 15? years. If you don’t know about them, that’s not my fault.

2.- You use the words "should" and "shouldn’t" a lot, but "sorry," welcome to the world of open source. I think it’s a great contribution. You don’t. OK. Don’t use it. End of discussion. I agree this won’t lead to anything really useful, so it's just you trying to impose your opinion on others.

3.- Regarding payment: Don’t worry. Several people, after I published the custom palettes, told me they were enjoying them— not you, of course.

Finally, as I’m getting tired of this useless discussion, I’ll say this again: it is a preamble to a major feature that other emulators, and real machines, already have. You don’t know about it? OK. So, what discourages me isn’t two devs talking; it’s ignorance talking. "Sorry."

**Comment by leiradel** [comment]
My two cents: variations of the Spectrum palette like the original one from Fuse, the one from Wikipedia etc. are a nice addition to the core. The other ones should be implemented in RetroArch as shaders, since they don't have anything to do with the original ZX Spectrum. If they're implemented as shaders, they could be enjoyed in other systems as well, just like i.e. CRT shaders.

**Comment by jfroco** [comment]
@HeuristicPerson and @leiradel 

Several emulators already support custom palettes, so you could say it just modernizes the emulator a little. However, that is not the main reason.

This is just an intermediate step to support games with "embedded" custom palettes. (This is quite complex, as not even the upstream emulator supports it.) These palettes are "in" the code of the games, so no, **it can't be implemented in a shader**.

This feature is available in several machines and emulators, and it can even be implemented in real machines by changing the ULA.

Example:
image

**Comment by leiradel** [comment]
@jfroco I think the new color palettes are great, but I also think you're confusing "core" for "emulator". A Libretro core should only emulate the system, effects like color swaps belong to the Libretro frontend, i.e. RetroArch.

As an example, will you implement all sorts of CRT filters in fuse-librero? Of course not, the intent is to make these filters usable with every core, which is why they belong to the frontend.

If you implement your palettes in the Frontend, not only fuse-libretro users will be able to enjoy them, but also the users of every other system for which there's a Libretro core available.

**Comment by zzedmore** [comment]
At the end of the day they're not doing any harm being there. The C64 core has pallettes and the Gameboy core etc. I hope @jfroco can port some more features from the source FUSE emu to this libretro one 😄

**Comment by jfroco** [comment]
@leiradel Thank you for the explanation, but I'm not confused.

Custom palettes should be implemented on the core if the game itself changes the palette during runtime, which is, as I've said several times, the final purpose of implementing changing palettes on the fly on the core.

This is a feature that has been available on several machines, emulators and custom ULA during years. 

Unfortunately, as I've explained this several times, and you insist that I'm wrong or, now, "confused", so this discussion is useless because I don't want to be confrontational with people that have contributed to this core.

**Comment by leiradel** [comment]
@jfroco you can also change it on the frontend during runtime. I think the palettes are great, and should be enjoyed by all systems, not only the ZX Spectrums. Having it only inside one core is too limiting. Imagine a C64 emulator with the speccy palette.

**Comment by jfroco** [comment]
@leiradel no, you can't.

This is how a game changes the palette during runtime:

```
ld bc, 0xbf3b ; register select
ld a, 64 ; mode group
out (c), a ;
ld a, 1 ;
ld b, 0xff ; choose register port
out (c), a ; turn palette mode on
xor a ; first register

setreg:

ld b, 0xbf ; choose register port
out (c), a ; select register
ex af, af' ; save current register select
ld a, (hl) ; get data
ld b, 0xff ; choose data port
out (c), a ; set it
ex af, af' ; restore current register
inc hl ; advance pointer
inc a ; increase register
cp 64 ; are we nearly there yet?
jr nz, setreg ; repeat until all 64 have been done
ei ; enable interrupts
ret ; return

; this is where the actual data is stored. The following is an example palette.

registers:

db 0x00, 0x02, 0x18, 0x1b, 0xc0, 0xc3, 0xd8, 0xdb ; INK
db 0x00, 0x02, 0x18, 0x1b, 0xc0, 0xc3, 0xd8, 0xdb ; PAPER
db 0x00, 0x03, 0x1c, 0x1f, 0xe0, 0xe3, 0xfc, 0xff ; +BRIGHT
db 0x00, 0x03, 0x1c, 0x1f, 0xe0, 0xe3, 0xfc, 0xff ;
db 0xdb, 0xd8, 0xc3, 0xc0, 0x1b, 0x18, 0x02, 0x00 ; +FLASH
db 0xdb, 0xd8, 0xc3, 0xc0, 0x1b, 0x18, 0x02, 0x00 ;
db 0xff, 0xfc, 0xe3, 0xe0, 0x1f, 0x1c, 0x03, 0x00 ; +BRIGHT/
db 0xff, 0xfc, 0xe3, 0xe0, 0x1f, 0x1c, 0x03, 0x00 ; +FLASH

terminating_byte:

db 0x0d 
```

Please, explain how the frontend can interpret this and the palette change using a shader or similar. 

Again, useless discussion as you just want to be right, not trying to understand a different position, even though I've mentioned this several times.

**Comment by leiradel** [comment]
@jfroco which peripheral is that? I couldn't find anything that uses port 0x3b. Emulating new peripherals is always a good addition to the core.

**Comment by jfroco** [comment]
@leiradel It's implemented in several peripherals, machines and emulators. This is the official specification: https://zxdesign.itch.io/ulaplus

**Comment by leiradel** [comment]
Ah nice! I was searching for 0x3b only, didn't realize that it used the full 16-bits for the port address.

I think actually adding ULAplus support to the core would be more beneficial than hardcoding some palettes attached to a core option though.

**Comment by jfroco** [comment]
> This is just an intermediate step to support games with "embedded" custom palettes.

@leiradel That's what I have been saying for a week :(

**Comment by leiradel** [comment]
I think it was just bad communication then, at least I wasn't aware of the ULAplus and that your intent is to add support for some custom palettes while preparing ULAplus support. It will be definitely a nice addition.

**Pull request merged**
