### PR TITLE
Update to Fuse 1.6.0 and libspectrum 1.5.0

### PR DESCRIPTION
**Pull request by tomconte**

### CODE REVIEW

**Comment by leiradel** [comment]
I'm quite sure this has been added in error: `fuse/The Hobbit v1.2.tzx`

**Comment by tomconte** [comment]
@leiradel @Gazdaman I think this PR is ready for review now... All checks pass and I have put in a workaround for the weird `getup_long` crash on RPi. I have squashed all the changes and only kept separate commits for the changes I had to make to the Fuse code proper.

I will try to ping the Libretro Discord too!

**Comment by tomconte** [comment]
Ping @twinaphex ?

**Comment by twinaphex** [comment]
Honestly it's about time this core gets updated. So unless there are really serious reasons for not wanting to merge this, I'm inclined to just brute force this through.

**Comment by twinaphex** [comment]
Hi there @tomconte , please ping me on Discord. My name there is Autechre.

https://discordapp.com/invite/27Xxm2h

This PR currently fails for several platform targets and requires your attention. It'd be best if we just deal with this through real-time communication vs. Github.

**Comment by twinaphex** [comment]
Reverting this for now because it takes some effort to fix these platforms again. @tomconte will be working in a branch on this revised version and then we can push a PR to master again once all platforms are building again.

**Comment by snoofly** [comment]
Any news on the Vita port?
The retroarch nightly fuse builds for vita crash when trying to load a rom since the merge.
I checked a fuse self from the 7th (1.1.1) and it works fine.
Thanks

**Pull request merged**
